### ISSUE TITLE
some more items to add!

### ISSUE THREAD

**Issue by gbathree** [brycejohnston/awesome-agriculture#7]
Lots of open source ag projects here:

Openteam.community

And also

goatech.org (conference + community)
forum.goatech.org (discussion forum)
https://agopengps.discourse.group/ (another discussion forum)

(self plug!) -->
surveystack.io is used as a data input tool for farm research projects (realfoodcampaign.org, general mills, ESMC, others).

But definitely look around through the openteam and goat lists and forums - lots of great additional folks to add to your list.

Thanks for creating this list!

**Comment by brycejohnston** [comment]
@gbathree thanks for the suggestions! Here are the contributing guidelines if you want to make a pull request to add them: https://github.com/brycejohnston/awesome-agriculture/blob/master/contributing.md

Those first several links could probably go under a new 'Community' category. As far as the surveystack.io, if that is a free and open source platform that others can run on their own servers for their own surveys, you could probably link to the code repos under the farm management and record keeping section.

Thanks!
